"""Add automation fields batch mode

Revision ID: 14c203bef772
Revises: 
Create Date: 2026-07-13 14:19:31.303317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c203bef772'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_generados', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_reportes_generados_authorized_by_usuarios'), 'usuarios', ['authorized_by'], ['id'])

    with op.batch_alter_table('resultados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_row_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validation_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('authorization_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados', schema=None) as batch_op:
        batch_op.drop_column('authorization_status')
        batch_op.drop_column('validation_status')
        batch_op.drop_column('source_row_number')

    with op.batch_alter_table('reportes_generados', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reportes_generados_authorized_by_usuarios'), type_='foreignkey')

    # ### end Alembic commands ###
