"""add_fuente_to_resultados

Revision ID: 6bcb55904e44
Revises: 9b8eeee64818
Create Date: 2026-08-07 15:26:51.524403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcb55904e44'
down_revision: Union[str, Sequence[str], None] = '9b8eeee64818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_reportes_generados')
    with op.batch_alter_table('resultados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuente', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados', schema=None) as batch_op:
        batch_op.drop_column('fuente')

    op.create_table('_alembic_tmp_reportes_generados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), nullable=False),
    sa.Column('lote_id', sa.INTEGER(), nullable=True),
    sa.Column('folio', sa.VARCHAR(), nullable=False),
    sa.Column('ruta_archivo', sa.VARCHAR(), nullable=False),
    sa.Column('fecha_generacion', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('generado_por', sa.INTEGER(), nullable=True),
    sa.Column('estado', sa.VARCHAR(), nullable=True),
    sa.Column('authorized_at', sa.DATETIME(), nullable=True),
    sa.Column('authorized_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['authorized_by'], ['usuarios.id'], name=op.f('fk_reportes_generados_authorized_by_usuarios')),
    sa.ForeignKeyConstraint(['generado_por'], ['usuarios.id'], name=op.f('fk_reportes_generados_generado_por_usuarios')),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_carga.id'], name=op.f('fk_reportes_generados_lote_id_lotes_carga')),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name=op.f('fk_reportes_generados_paciente_id_pacientes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reportes_generados'))
    )
    # ### end Alembic commands ###
